### ISSUE TITLE
No excel file written

### ISSUE THREAD

**Issue by axi92** [crocokyle/basic-ping-logger#1]
I start it like this `python3 pinger.py` when I STRG+C then I get this error:

```
Starting ping logger at 2023-04-17 09:46:15.258675...


   
exit
^CTraceback (most recent call last):
  File "/home/plehner/Workspace/git/basic-ping-logger/pinger.py", line 106, in <module>
    main_loop(args.output_file, target=args.target, save_frequency=args.save_frequency)
  File "/home/plehner/Workspace/git/basic-ping-logger/pinger.py", line 75, in main_loop
    ping_response: str = run_command(['ping', target])
  File "/home/plehner/Workspace/git/basic-ping-logger/pinger.py", line 12, in run_command
    raw_output = subprocess.run(command, stdout=subprocess.PIPE)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1139, in communicate
    stdout = self.stdout.read()
KeyboardInterrupt
```

And no excel file is written. I have run it for days.

**Comment by crocokyle** [comment]
Thanks for opening an issue. I haven't set this script up to run on Linux although it should be pretty easy to modify for that. 

I can try to update it to work on Linux this week.
